// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BasePayload = {
  value: any;
  displayValue: string | null;
  displayStyle: string | null;
  extraFields: Map<string, any> | null;
};
