// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellContent } from "./CellContent";

export type CellMeta = {
  hasDisplayFormatter: boolean | null;
  displayStyleClass: string | null;
  defaultCellContent: CellContent;
};
