// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellMeta } from "./CellMeta";

export type CellMetaMap = { [key in string]?: CellMeta };
