// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayCellResult } from "./DisplayCellResult";

export type DisplayCellResults = Array<DisplayCellResult>;
