// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveSheetICell } from "./SaveSheetICell";

export type SaveSheetRequest = {
  sheetPath: string;
  cells: Array<SaveSheetICell>;
};
