// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasePayload } from "./BasePayload";

export type CellContent = { type: string, payload: BasePayload, };
