// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayCellResult = { row: number, col: number, ok: boolean, displayValue: string | null, error: string | null, };
