[package]
name = "sql-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "55.2.0"
duckdb = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
