// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BasePayload = { value: any, displayValue: string | null | undefined, displayStyle: string | null | undefined, extraFields: Record<string, any>, };
