// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellContent } from "./CellContent";

export type FrontedSheet = {
  cells: { [key in string]?: CellContent };
  rowHeader: { [key in string]?: CellContent } | null;
  colHeader: { [key in string]?: CellContent } | null;
  sheetId: string;
  sheetType: string;
  sheetName: string;
  hasRowHeader: boolean;
  hasColHeader: boolean;
  rowCount: number;
  colCount: number;
  cellWidth: number;
  cellHeight: number;
  defaultCellContent: string;
};
