// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ICell } from "./ICell";

export type FrontedSheetData = { type: string, sheetName: string, rowCount: number, colCount: number, cellWidth: number, cellHeight: number, cells: Array<ICell>, fields: Record<string, any>, };
